version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    cooldown:
      default-days: 3
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    cooldown:
      default-days: 3
    schedule:
      interval: 'weekly'
