name: Usage Count

on:
  workflow_dispatch

jobs:
  usage-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: api-search
        with:
          debug: true
          result-encoding: string
          script: |
            const result = await github.rest.search.code({
              q: 'gradle-update+update-gradle-wrapper-action+in:file+language:yaml+path:.github/workflows'
            })
            console.log(JSON.stringify(result, null, 2))
            console.log(result.data.total_count)
            return result.data.total_count || -1
      - name: Get result
        run: echo "${{steps.api-search.outputs.result}}"
